# This is a basic workflow to help you get started with Actions

name: cache

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cache:
    outputs:
      changes: ${{ steps.auto-commit-action.outputs.changes_detected }}
      version: ${{ steps.download.outputs.version }}
      cid: ${{ steps.web3.outputs.cid }}
      url: ${{ steps.web3.outputs.url }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - id: download
        run: ./download.sh
        shell: bash
      - id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        commit_message: "VS Code Server ${{ steps.download.outputs.version }}"
        tagging_message: "v${{ steps.download.outputs.version }}"
      - uses: actions/upload-artifact@v3
        with:
          path: $GITHUB_WORKSPACE/bin
      - if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: '$GITHUB_WORKSPACE/bin'
